#!/bin/sh
 
# Exit on error
set -e
 
# Source debconf library.
. /usr/share/debconf/confmodule
 
# Ask questions only if first time installation
PKG=poppet

STATUS=$(dpkg -s ${PKG} 2> /dev/null | grep Status: | cut -d' ' -f4)


db_input high poppet/mysql-host  || true
db_input high poppet/mysql-root-user  || true    
db_input high poppet/mysql-root-pass  || true
db_input high poppet/mysql-db-name  || true

# Show interface
db_go || true
set +e

